api_key: sk-proj-wmExG8KsPuL9RgAkUJuuT3BlbkFJbGWYOUBu7SzkI9LHdEwF

persona_config:
  persona_path: G:\Edu\TUM_Tech_Challenge\munetz\ai_core\models\chatgpt_based_models_utils\personas\information_extraction
  persona_file_name: persona2.txt

doc_default_path: G:\Edu\TUM_Tech_Challenge\munetz\ai_core\python_scripts\shared_docs

num_to_retry_prompt : 3

info_to_extract:
  - emails
  - phone_numbers
  - location
  - author
  - partners
