api_key: sk-proj-wmExG8KsPuL9RgAkUJuuT3BlbkFJbGWYOUBu7SzkI9LHdEwF
persona_config:
  persona_path: G:\Edu\TUM_Tech_Challenge\munetz\ai_core\models\chatgpt_based_models_utils\personas\chatbot
  persona_file_name: persona2.txt
thread_id: thread_3lWWFtwjpBY2enBRbflNByb3
